### ISSUE TITLE
create stickers with logo

### ISSUE THREAD

**Issue by mrayson** [TIDE-ITRH/gptide#15]

**Comment by astfalckl** [comment]
https://www.ozstickerprinting.com/?gclid=CjwKCAjw6MKXBhA5EiwANWLODBaj5KX-tNbkFEnClsiWQNqyXy8OxjrLA4dLdfpiqZ_SeYkWOLldQBoCQmkQAvD_BwE

**Comment by mrayson** [comment]
ordered...

**Comment by mrayson** [comment]
Done
