### ISSUE TITLE
strip down the parts of oceanoi that we need above

### ISSUE THREAD

**Issue by iosonobert** [TIDE-ITRH/gptide#6]

**Comment by iosonobert** [comment]
oceanoi.mcmc_oi moved to gptide.mcmc
oceanoi.driveroi moved to gptide.mle
oceanoi.oidask moved to gptide.gpdask

Haven't tested the MLE code since moving. The example notebooks should include this.

**Comment by mrayson** [comment]
I have updated the mle code and created an example [in this commit](https://github.com/TIDE-ITRH/gptide/commit/5d50a7a50fa6d0571f3e52f8e45c900df0d6e793). Still need to add docstrings to the mle function plus add the example to the docs.

**Comment by iosonobert** [comment]
Docstrings and more tests needed. Separate issue.
