### ISSUE TITLE
Standardise interface for mle and mcmc 

### ISSUE THREAD

**Issue by iosonobert** [TIDE-ITRH/gptide#7]
Going to track interface differences here before jumping in and changing everything. If it turns out to be unnecessary will delete. 
- [x] mcmc takes one 'priors' input and ncovparams to distinguish meanfunc priors from covfunc priors. mle takes two different priors inputs = 'covparams_ic' and 'meanparams_ic' [it then combines these internally]
- [x]  meanfunc and meanparams should be made optional with the mle call

**Comment by mrayson** [comment]
Agree that this needs updating. An idea is to use the mle approach in the mcmc function but input `covpriors` and `meanpriors` instead. 

A side issue is that the meanfunc and meanparams should be made optional with the mle call.

**Comment by iosonobert** [comment]
Yeah I prefer the mle approach

**Comment by iosonobert** [comment]
Done and tested with both docs/examples and with the four gpnliw examples
  
More could be done but closing this for now.
